job('First-Maven-Project-Via-DSL')
{
 description("First Maven Job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
 scm
 {
   git("https://github.com/sureshkumar-devops/mavenproject.git",master)
 }
 triggers
 {
   scm('* * * * *')
 }  
 steps
 {
  maven('clean package','pom.xml')
 }
 publishers
 {
    archiveArtifacts '**/*.jar'
 }
}
